### ISSUE TITLE
Problem running the module

### ISSUE THREAD

**Issue by markive** [centogram/TiIntercomAndroid#1]
Hi Centrogram,

I have an issue running this module. I get the following error:

```

Unable to find explicit activity class (com.myapp/io.intercom.android.sdk.activities.MainActivity); have you declared this activity in your AndroidManifest.xml?

Source: TiIntercom.presentConversaionList();
```

I'm not sure if this helps, but I definitely can't get this to work: http://stackoverflow.com/questions/3433778/android-content-activitynotfoundexception

Do I need to put anything else in an AndroidManifest.xml inside my App itself? Also I assume I have to include the resources in /platform/android?

**Comment by jerodfritz** [comment]
Hey Markive - Just tested the module in one of my projects with and it ran fine.  Attached is the compiled version I'm using.  Perhaps I committed an old version.   Here is a version straight from the project I tested.  
[ti.intercom.android.zip](https://github.com/centogram/TiIntercomAndroid/files/197828/ti.intercom.android.zip)

Also, I have a few updates to handle Push Notifications similar to the iOS module updates I did a few weeks back I'm going to release for a 1.0.1 at some point.

**Comment by markive** [comment]
Hi Centogram, thanks for checking.. It was because I'm using a custom AndroidManifest.xml file.

If anyone else has the same problem just add this to your custom AndroidManifest.xml file:

```
<activity android:name="io.intercom.android.sdk.activities.MainActivity" android:configChanges="screenSize|orientation" android:exported="false" android:launchMode="singleTop" android:theme="@style/IntercomSDK_PanelTheme" android:windowSoftInputMode="stateUnchanged|adjustResize"/>
        <activity android:name="io.intercom.android.sdk.attachments.AttachmentActivity" android:configChanges="screenSize|orientation" android:exported="false" android:theme="@style/IntercomSDK_AttachmentTheme" android:windowSoftInputMode="stateUnchanged|adjustResize"/>
        <activity android:name="io.intercom.android.sdk.conversation.lightbox.LightboxActivity" android:configChanges="screenSize|orientation" android:exported="false" android:theme="@style/IntercomSDK_AttachmentTheme" android:windowSoftInputMode="stateUnchanged|adjustResize"/>
```
