### ISSUE TITLE
3.0 Upgrade

### ISSUE THREAD

**Issue by jerodfritz** [centogram/TiIntercomAndroid#5]
Hi @minhnc .  Would you be available to upgrade this module to the latest Intercom SDK?  We would be happy to compensate you for your time to help.
- Jerod

**Comment by jerodfritz** [comment]
I've been experimenting with Hyperloop and the integration of third party sdks is pretty straightforward.  I'll update main repo with a note to the effect that this project will no longer be updated along steps to integrate directly in your project without need for this module any longer.

**Comment by minhnc** [comment]
Sorry for late response as Im out of town right now with very limit resources. Hyperloop is great but available for Pro only. Hope Indie devs could use Hyperloop modules soon ( Pro users could develop Hyperloop modules )
